// <auto-generated />
using MVC.Day3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Day3.Migrations
{
    [DbContext(typeof(BugsContext))]
    partial class BugsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Day3.Data.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ergonomic Granite Car",
                            Severity = 2,
                            Title = "Electronics, Sports & Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Soft",
                            Severity = 0,
                            Title = "Health & Home"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Designer",
                            Severity = 1,
                            Title = "Electronics & Jewelery"
                        },
                        new
                        {
                            Id = 4,
                            Description = "morph",
                            Severity = 2,
                            Title = "Toys, Health & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vermont",
                            Severity = 1,
                            Title = "Movies & Health"
                        },
                        new
                        {
                            Id = 6,
                            Description = "navigating",
                            Severity = 1,
                            Title = "Home"
                        },
                        new
                        {
                            Id = 7,
                            Description = "redundant",
                            Severity = 2,
                            Title = "Baby, Movies & Toys"
                        },
                        new
                        {
                            Id = 8,
                            Description = "neural",
                            Severity = 1,
                            Title = "Sports, Tools & Baby"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Oklahoma",
                            Severity = 2,
                            Title = "Baby & Shoes"
                        },
                        new
                        {
                            Id = 10,
                            Description = "SMTP",
                            Severity = 1,
                            Title = "Music & Garden"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Future",
                            Severity = 2,
                            Title = "Automotive"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Rubber",
                            Severity = 0,
                            Title = "Computers, Baby & Games"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Point",
                            Severity = 1,
                            Title = "Clothing & Games"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Fantastic Frozen Ball",
                            Severity = 1,
                            Title = "Electronics, Kids & Games"
                        },
                        new
                        {
                            Id = 15,
                            Description = "convergence",
                            Severity = 2,
                            Title = "Books & Games"
                        },
                        new
                        {
                            Id = 16,
                            Description = "haptic",
                            Severity = 2,
                            Title = "Tools, Baby & Sports"
                        },
                        new
                        {
                            Id = 17,
                            Description = "XSS",
                            Severity = 0,
                            Title = "Automotive"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Toys",
                            Severity = 2,
                            Title = "Jewelery & Tools"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Intelligent",
                            Severity = 1,
                            Title = "Garden"
                        },
                        new
                        {
                            Id = 20,
                            Description = "zero defect",
                            Severity = 2,
                            Title = "Clothing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
